name: Reset database

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Resetting the database
        run: |
          ssh $SSH_USER@$SSH_HOST "pushd ~/app/${{ github.head_ref }} && pm2 stop ecosystem.config.js && ./bin/create-db-copy ${{ secrets.DB_PASSWORD }} ${{ github.head_ref }} && pm2 restart ecosystem.config.js --name ${{ github.head_ref }} --env production --update-env && popd"
        env:
         SSH_USER: ${{ secrets.SSH_USER }}
         SSH_HOST: ${{ secrets.SSH_HOST }}
